version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-vol:/data
  web-app:
    image: ogiquel/python-webapp:1.0
    container_name: python-app
    ports:
      - "80:80"
    depends_on:
      - redis
volumes:
  redis-vol:
    name: redis-vol
